/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VL53L0X;

import i2c.sensor.VL53L0X;

public class App {
    public static void main(String[] args) {
        try {
            System.out.print("Initializing...");
            VL53L0X vl530x = new VL53L0X();
            System.out.println("[DONE]");

            System.out.println("Press Control-C to quit");

            int previousDistance = -1;

            while (true) {
                int distance = vl530x.range();

                if (distance != previousDistance) {
                    System.out.print(String.format("Range: %04dmm\r", distance));
                }

                try {
                    Thread.sleep(50);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
